import React, { Suspense } from "react";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: "300",
  subsets: ["latin"],
});

export const metadata = {
  title: "Task-Calendar",
  description: "Generated by Sagar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <Suspense>{children}</Suspense>
      </body>
    </html>
  );
}
